config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'results#new'
  resources :results
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :result
  belongs_to :category, optional: true
end

app/models/result.rb
class Result < ApplicationRecord
  has_many :events, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @results = Result.order(created_at: :desc).paginate(:page => params[:page], :per_page => 15)
  end

  def new
    @result = Result.new
  end

  def show
    @result = Result.find(params[:id])
  end

  def create
    @result = Result.new(result_params)
    matched_result = Result.find_by(queried_date: @result.queried_date)
    if matched_result
      @result = matched_result
    else
      @result.save
      scrape_and_save_events
    end
    redirect_to @result
  end

  private
  def result_params
    params.require(:result).permit(:queried_date)
  end

  def scrape_and_save_events
    date, month, year = @result.queried_date.strftime("%d %B %Y").split
    scrape_events(date, month, year)
    
    @events_in_category_raw.each_with_index do |list_of_events, category_index|
      events = list_of_events.xpath('li')
      events.each do |event|
        event_link_raw = event.css('a').first['href']
        full_link = absolute_link(event_link_raw)
        event_digest = scrape_event_digest(full_link)
        save_event(event_digest, category_index)
      end
    end
  end

  def scrape_events(date, month, year)
    content= HTTParty.get('https://en.wikipedia.org/wiki/Portal:Current_events/' + month + '_' + year + '#' + year + '_' + month + '_' + date,
      :headers =>{'Content-Type' => 'application/json'} )
    page = Nokogiri::HTML(content)
    events_section = page.css('table').css('table.vevent')[date.to_i - 1].css('tr').css('td.description')
    categories_raw = events_section.css('dl').css('dt') rescue nil
    if categories_raw
      @category_ids = []
      categories_raw.each do |category|
        found_category = Category.where('lower(name) = ?', category.text.downcase).first
        found_category ||= Category.create(:name => category.text)
        @category_ids << found_category.id
      end
      @events_in_category_raw = events_section.xpath('ul')
    else
      @events_in_category_raw = events_section.css('ul')
    end 
  end

  def scrape_event_digest(event_link)
    raw_content = HTTParty.get(event_link, :headers =>{'Content-Type' => 'application/json'})
    page = Nokogiri::HTML(raw_content)
    title = page.at('h1').text
    summary = page.xpath('//div[@class="mw-parser-output"]/p[./following-sibling::div[@id="toc"] ] ').to_s
    if summary.empty?
      summary = page.xpath('//div[@class="mw-parser-output"]/p[./following-sibling::div[starts-with(@class, "toc")]]').to_s
    end
    if summary.empty?
      summary = 'n/a'
    end
    image_link = page.xpath('//div[@class="mw-parser-output"]').css('a.image').first.attributes['href'].text rescue nil
    digest = {title: title, summary: summary, image_link: image_link}
  end

  def absolute_link(scraped_link)
    full_link = ''
    if !scraped_link.start_with?('/wiki')
      full_link = scraped_link
    else
      full_link = 'https://en.wikipedia.org' + scraped_link
    end
    full_link
  end

  def save_event(event_digest, category_index)
    new_event = Event.new(title: event_digest[:title], image_link: event_digest[:image_link], summary: event_digest[:summary])
    new_event.result = @result
    if @category_ids && @category_ids.any?
      new_event.category = Category.find(@category_ids[category_index])
    end
    new_event.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
  def format_date(full_timestamp)
    full_timestamp.strftime("%d/%m/%Y")
  end

  def show_link_if_events_found(result)
    if result.events.empty?
      '0'
    else
      link_to result.events.count, result
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiEvents</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.css" />
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'WikiDigest', root_path, :class => 'navbar-brand' %>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Previous Queries', results_path %></li>
          <li><%= link_to 'Search Wiki', new_result_path %></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    <br />
    <br />
    <br />
    <br />
  </body>
</html>

app/views/results/index.html.erb
<h1>Previous Queries</h1>

<% if @results.any? %>
  <table class="table">
    <tr>
      <th>
        Queried Date of Wiki-events
      </th>
      <th>
        Time the Query Was Made
      </th>
      <th>
        Number of Wiki-events Obtained
      </th>
    </tr>
    <% @results.each do |result| %>
      <tr>
        <td><%= format_date(result.queried_date) %></td>
        <td><%= result.created_at %></td>
        <td><%= show_link_if_events_found(result) %></td>
      </tr>
    <% end %>
  </table>

  <%= will_paginate @results %>
<% else %>
  <p>No searches have been made yet.</p>
<% end %>

app/views/results/new.html.erb
<div class="page-header">
    <h1>WikiDigest <small>provides a short version of Wikipedia events for a given day</small></h1>
  </div>

  <dl>
    <dt>The searchable date range is from 01/01/2000 till today.</dt>
    <dd>The more recent, the more reliable. Wikipedia earlier than 2010 appears to use different markup for the event section, and is also more prone to inconsistent markup and missing dates. (2004 and earlier is almost guaranteed to throw an exception)</dd>
    <dd>Note the majority of events prior to 2010 are not categorized in Wikipedia, so the parsed events during this period will not come with categories.</dd>
    <br />
    <dt>Search on the same date will be cached locally.</dt>
    <dd>An edit made on Wikipedia for an already searched date won't be reflected locally.</dd>
    <br />
    <dt>In the event that no events were obtained, or any parts of the events were missing for the day, the query is saved to indicate the attempted retrieval.</dt>
    <dd>For example, event summary will be 'n/a', or no events will be saved if no events are retrived for the date.</dd>
  </dl>

  <%= form_for @result do |f| %>
  <p>
    <%= f.label :queried_date,'Query Date' %><br>
    <%= f.text_field :queried_date, id: 'pickDate' %>
  </p>
 
  <p>
    <%= f.submit "Search" %>
  </p>
<% end %>
</div>
<script type="text/javascript">
  $(document).ready(function () {
    $('#pickDate').datepicker({
        format: "dd/mm/yyyy",
        startDate: "1/1/2000",
        endDate: '0d'
    });
  });
</script>

app/views/results/show.html.erb
<h4><%= @result.events.count %> Events retrieved for <%= format_date(@result.queried_date) %></h4>
<% if @result.events.empty? %>
  <p>There are no events found today.</p>
<% else %>
  <% @result.events.each_with_index do |event, index| %>
    <% if @result.events[index - 1] && @result.events[index - 1].category != event.category %>
      <br />
      <div class="row">
        <h2><%= event.category.name %></h2>
      </div>
    <% end %>
    <hr>
    <div class="row">
      <div class="col-md-12">
        <h4>
          <%= event.title %>
          <% if event.image_link %>
            <small>
              <%= link_to event.image_link, "https://en.wikipedia.org" + event.image_link %>
            </small>
          <% end %>
        </h4>
      </div>
      <div class="col-md-12"><% if event.summary %><%= event.summary.html_safe %><% end %></div>
    </div>
  <% end %>
<% end %>